name: build-backend
description: Builds a Java backend project and generate the associated Docker image & Helm chart, which can be cached. It also runs a Sonar scan (except for Renovate PRs).

inputs:
  app-name:
    description: Application name
    required: true

runs:
  using: "composite"

  steps:
    - name: Build API
      shell: bash
      run: |
        echo "Build API ${{ inputs.app-name }} completed !"
    
    - name: Upload API
      uses: asmaelkb/AOC2023/upload-backend@main
      with:
        app-name: ${{ inputs.app-name }}