name: create-health-version-files
description: 'Create health and version files once build is done'
inputs:
  mytoken:
    description: 'Token'
    type: string
    required: true

runs:
  using: "composite"
  steps: 
    - name: Display secret
      shell: bash 
      run: | 
        echo ${{ inputs.mytoken }}