
name: Run scopes
description: Sélectionne les scopes à exécuter
title: "Run scopes"
labels: ["run-scopes"]   # Sert à filtrer côté workflow
body:
  - type: markdown
    attributes:
      value: |
        Coche les scopes à exécuter ci-dessous. Tu peux en choisir plusieurs.

  - type: checkboxes
    id: scopes
    attributes:
      label: Scopes
      options:
        - label: scope1
        - label: scope2
        - label: scope3
        - label: search
        - label: billing
        - label: email
        - label: auth
        - label: reporting
        - label: scope5
        - label: scope6
        - label: scope7
        - label: scope8
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Qui demande (optionnel)
      description: Pour la traçabilité
