name: Clean workflow history

on:
  schedule:
    - cron: "0 5 1 * *" # Monday at 5:00
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean
        required: false

jobs:
  call-workflow-clean-runs:
    uses: asmaelkb/AOC2023/.github/workflows/reusable-clean.yml@main
    with:
      dry-run: ${{ inputs.dry-run || 'false' }}
    secrets: inherit
