on:
  workflow_dispatch:
    inputs:
      target_database:
        description: Target database to release
        type: choice
        options:
          - db-A
          - db-B
          - db-C
        required: true
      release:
        description: Make release
        type: boolean
        required: true
      release_version:
        description: Release version
        type: string
        required: true
      
jobs:
  dispatch-backend-release:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch 
        shell: bash
        run: | 
          echo "Dispatching Back-end Release Workflow for database: ${{ github.event.inputs.target_database }}"