name: Execute Job Matrix

on: 
  workflow_dispatch:
    inputs:
      app:
        description: 'Application name to build'
        required: true

jobs:
  execute-job-matrix:
    uses: asmaelkb/AOC2023/.github/workflows/job-matrix.yml@main
    with:
      app: ${{ inputs.app }}
      environment: 'dev'