# This workflow is to test if it is possible to create matrix for a job in a callable workflow
name: Build single API, or Engine/Editor API

on:
  workflow_call:
    inputs:
      app:
        description: 'Application name to build'
        type: string
        required: true

jobs:
  build-api:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    if: github.event.repository.name != 'switchboardengine'
    steps:
      - name : Build & Upload API
        uses: asmaelkb/AOC2023/build-backend@main
        with:
          app-name: ${{ matrix.app }}

  build-editor-engine-api:
    runs-on: ubuntu-latest
    environment: ${{ matrix.app }}-${{ inputs.environment }}

    if: github.event_name == 'workflow_dispatch'

    strategy:
      matrix:
        app: [editor, engine]

    steps:
      - name : Build & Upload API
        uses: asmaelkb/AOC2023/build-backend@main
        with:
          app-name: ${{ matrix.app }}


