# This workflow is to test if it is possible to create matrix for a job in a callable workflow
name: Build single API, or Engine/Editor API

on:
  workflow_call:

jobs:
  build-editor-engine-api:
    runs-on: ubuntu-latest
    environment: ${{ matrix.app }}-${{ matrix.env }}

    if: github.event_name == 'workflow_dispatch'

    strategy:
      matrix:
        app: [editor, engine]
        env: [dev, data]

    steps:
      - name : Verify environment
        run: |
          echo "Environment is ${{ vars.RESULT }}"
          echo "Application is ${{ matrix.app }}"



