# Workflow to clean runs of all workflows in a repository
name: Reusable Clean Workflow Runs

on:
  workflow_call:
    inputs:
      last-success:
        description: Number of last successful workflows to keep
        type: number
        required: false
        default: 1
      last-failure:
        description: Number of last failed workflows to keep
        type: number
        required: false
        default: 5
      dry-run:
        description: For debugging purposes
        type: string
        required: false
        default: false

jobs:
  clean:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete ${{ inputs.last-success }} last successful workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          dry_run: ${{ inputs.dry-run }}
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ inputs.last-success }}
          delete_run_by_conclusion_pattern: success
          check_pullrequest_exist: true     # In order to not delete PR workflows runs of active PRs

      - name: Delete ${{ inputs.last-failure }} last failed workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          dry_run: ${{ inputs.dry-run }}
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ inputs.last-failure }}
          delete_run_by_conclusion_pattern: failure
          check_pullrequest_exist: true     # In order to not delete PR workflows runs of active PRs