name: Summary

on:
  workflow_dispatch:


jobs: 
  summary:
    runs-on: ubuntu-latest

    outputs:
      summary: ${{ steps.summary.outputs.summary }}
    steps:
      - name: Summary
        id: summary
        run: |
          SUMMARY="{
            echo 'POEditor files have been published under assets/translation/swb-editor/3.41 : '
            echo 'es.txt, fr.txt, ja.txt, pt.txt, ru.txt, zh.txt'
            }"
          
          echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
  
  summary-matrix:
    needs: summary
    runs-on: ubuntu-latest
    steps:
      - name: Summary Matrix
        run: |
          {
            echo "## 🗄️ Release Summary"
            echo "| Property | Value |"
            echo "|---|---|"
            echo "| Message | hello ! |"
          } >> $GITHUB_STEP_SUMMARY

          ${{
            needs.summary.outputs.summary
          }} >> $GITHUB_STEP_SUMMARY

          