name: Summary

on:
  workflow_dispatch:


jobs: 
  summary:
    runs-on: ubuntu-latest

    outputs:
      summary: ${{ steps.summary.outputs.summary }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Summary
        id: summary
        run: |
          UPLOADED_FILES=()

          for directory in $(ls); do
            UPLOADED_FILES+=("$directory")
          done

          FILES_LIST=$(IFS=', '; echo "${UPLOADED_FILES[*]}")
          echo $FILES_LIST
          echo "summary=$FILES_LIST" >> "$GITHUB_OUTPUT"
  
  summary-matrix:
    needs: summary
    runs-on: ubuntu-latest
    steps:
      - name: Summary Matrix
        run: |
          {
            echo "## 🗄️ Release Summary"
            echo "| Property | Value |"
            echo "|---|---|"
            echo "| Message | hello ! |"
          } >> $GITHUB_STEP_SUMMARY

      - name: Display Summary
        run: |
          {
            echo "## 📦 POEditor files publication"
            echo
            echo "All below POEditor files have been published on S3 to folder \`assets/translation/swb-editor/${{ needs.compute-versions.outputs.release-branch-version }}/\`"
            echo "| File |"
            echo "|------|"

            IFS=',' read -ra files <<< "${{ needs.summary.outputs.summary }}"
            for file in "${files[@]}"; do
              file=$(echo "$file" | xargs) # trim spaces
              echo "| \`$file\` |"
            done
          } >> "$GITHUB_STEP_SUMMARY"



          